version: '3.9'

services:
  postgres_tests:
    image: postgres:16.1
    container_name: postgres_tests
    ports:
      - 5777:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_u
      - POSTGRES_PASSWORD=test_p
    volumes:
      - postgres_tests_data:/var/lib/postgresql/data

volumes:
  postgres_tests_data:
