"""empty message

Revision ID: 17cfa02e1d10
Revises: 76f6825a7bd8
Create Date: 2024-05-23 11:09:24.192385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17cfa02e1d10"
down_revision: Union[str, None] = "76f6825a7bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("post_tags_tag_id_fkey", "post_tags", type_="foreignkey")
    op.drop_constraint("post_tags_post_id_fkey", "post_tags", type_="foreignkey")
    op.create_foreign_key(
        None, "post_tags", "tags", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "post_tags", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post_tags", type_="foreignkey")
    op.drop_constraint(None, "post_tags", type_="foreignkey")
    op.create_foreign_key(
        "post_tags_post_id_fkey", "post_tags", "posts", ["post_id"], ["id"]
    )
    op.create_foreign_key(
        "post_tags_tag_id_fkey", "post_tags", "tags", ["tag_id"], ["id"]
    )
    # ### end Alembic commands ###
